### ISSUE TITLE
Nuget package for WS6

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/remarkable#1]
Hi!

I'm testing WS6 but the Nuget package only references WS4, for this lib.

Same problem with WebSharper.Google.Maps.

Regards,
Alex

**Comment by granicz** [comment]
There are dozens of such extensions, yes. WS6 now has a growing "core stack" of ~20 core extensions (charting, etc.) with up to date bindings, all the rest is currently lagging behind at 4.x. Compiling those to WS6 would be easy, but the underlying bindings would still point to the old library versions, hence they have been put on a backburner for the time being. If you would like to help moving the ones you need to the latest libraries, let me know, I am happy to give some pointers.

**Comment by granicz** [comment]
(The reason for all this is that we are changing the compiler output to work with the latest JS libraries, many of which have moved to a module/class-based structure. Essentially, when we are done supporting those with WebSharper 7, we will bring back up to date all existing extensions - and this is where we can definitely use the community's help!)

**Comment by AlexPeret** [comment]
thanks, Adam!

I'll make a local copy and update them for now. Already did for one I've wrote for FileDrop.js, without problem.

> .. Essentially, when we are done supporting those with WebSharper 7, we will bring back up to date all existing extensions - and this is where we can definitely use the community's help!)

I'll follow along with the project and will be glad to help.

Thanks!
Alex
